import { useState, useEffect } from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/app/components/ui/floating-navbar";
import { IconHome, IconMessage, IconUser } from "@tabler/icons-react";

// Define your navigation items here
const navItems = [
  {
    name: "Home",
    link: "/",
    icon: <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "About",
    link: "/about",
    icon: <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
  {
    name: "Contact",
    link: "/contact",
    icon: <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />,
  },
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "<Name Pending>",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(false);

  const handleNavigationClick = () => {
    setLoading(true);
  };

  useEffect(() => {
    if (loading) {
      const timer = setTimeout(() => {
        setLoading(false);
      }, 1000); // Duration of the animation

      return () => clearTimeout(timer);
    }
  }, [loading]);

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Loading overlay */}
        <div className={`loading-overlay ${loading ? 'active' : ''}`}></div>

        {/* Include the FloatingNav component */}
        <FloatingNav navItems={navItems} onNavClick={handleNavigationClick} />

        <main className={`fade-in ${!loading ? 'show' : ''}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
